on: [push, pull_request]
jobs:
  pkgs:
    strategy:
      matrix:
        package:
          - ld-audit-prefer-runpath
          - ld-audit-prefer-runpath-dbg
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          sudo apt-get -y install binfmt-support qemu-user-static
          sudo mkdir -p /etc/nix
          echo "extra-platforms = ${{ matrix.arch }}-linux" | sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon
      - run: nix build -L --no-update-lock-file .#packages.${{ matrix.arch }}-linux.${{ matrix.package }}
